### PR TITLE
feat: Implement basic handling of Alias for breaking changes

### PR DESCRIPTION
**Pull request by Georggi**

### CODE REVIEW

**Comment by pawamoy** [comment]
Thanks a lot! Could you add some tests?

**Comment by pawamoy** [comment]
Thanks for the update. Since both tests are very similar, I'd prefer that we combine them, if possible (easier to maintain). I'll try to do that if you don't mind.

**Comment by pawamoy** [comment]
Just pushed my changes. Let me know what you think. IMO it's looking good and we can merge :slightly_smiling_face:

**Comment by Georggi** [comment]
My only concern is that we removed a more basic case with no alias. I think there should still be a separate assert at least that would not include init module.

**Comment by pawamoy** [comment]
Good point, I've added back tests without aliases :slightly_smiling_face:

**Comment by pawamoy** [comment]
Thanks again!

**Pull request merged**
