### PR TITLE
fix: reporting the attribute who lost their value

### PR DESCRIPTION
**Pull request by gpuligundla**
This PR Address the #218 issue. 

Describe the bug
For example, going from:

```
class A:
    b: int | None = None
```
to

```
class A:
    b: int
```
will report

`Attribute value was changed: None -> None`

Now modified to 

`Attribute value was changed: None -> unset`

### CODE REVIEW

**Review by pawamoy — CHANGES_REQUESTED** [review]
Thanks!

It would be better to pass "unset" to the breakage instance rather than modifying the value in the actual attribute 🙂

**Comment by gpuligundla** [comment]
> Thanks!
> 
> It would be better to pass "unset" to the breakage instance rather than modifying the value in the actual attribute 🙂

Changed it

**Review by pawamoy — COMMENTED** [review]
Thanks. I realise it needs an `else` clause, otherwise it would yield both breakages.
Could you also add a test :) ?

**Comment by gpuligundla** [comment]
> Thanks. I realise it needs an `else` clause, otherwise it would yield both breakages. Could you also add a test :) ?

ah! yeah sorry for being noob, i assumed it as return keyword

**Review by pawamoy — APPROVED** [review]
No worries! And thanks for the update :slightly_smiling_face: LGTM now, merging!

**Pull request merged**
