### PR TITLE
test: try to parse randomly generated code

### PR DESCRIPTION
**Pull request by 15r10nk**
Use pysource-codegen and pysource-minimize combined to find source code which can not be parsed.

some results:

``` python
@'some const text'[name_3]
async def name_5(): # type: some text
    pass
```

``` python
@lambda: name_5
class name_5:
    name_4 = name_0
```

``` python
@1[name_0]
async def name_3(): # type: ignoresome text
    pass
```

It might be that these examples are not as minimal as they could be (the type strings are propably not important). But I think that they are a good starting point.

### CODE REVIEW

**Comment by pawamoy** [comment]
Oh, thanks a lot! I already have written a `fuzz` task though, let me push it so you can see :sweat_smile: 
It doesn't minimize code though, so we might be able to reuse that part :slightly_smiling_face:

**Comment by pawamoy** [comment]
Have a look at https://github.com/mkdocstrings/griffe/blob/main/duties.py#L302 :slightly_smiling_face:

**Comment by 15r10nk** [comment]
No problem. You don't have to merge this merge-request. I wanted to show what I mean with the minimization part. I hope it will help you to fix some bugs.

**Comment by pawamoy** [comment]
Yes I already fixed 3 bugs thanks to pysource-codegen :heart: :rocket: 
And thanks for the PR, I didn't think we could use pysource-minimize like this, I will integrate it in my fuzz task!

**Comment by 15r10nk** [comment]
Great :+1:

The SystemErrors are from cpython itself https://github.com/python/cpython/issues/109219 It really looks for me like you are using a pre-release. 
Could you please verify this. 

We should report a bug if this is not the case.

**Comment by pawamoy** [comment]
Yep, I [answered on the issue](https://github.com/mkdocstrings/griffe/issues/215#issuecomment-1751411606), I was indeed using 3.12.0rc1. I've upgraded to 3.12.0, ran many and there's no SystemError anymore.

**Comment by pawamoy** [comment]
Sorry for the notifications, I was just testing something. I reused your code in another commit, marking you as co-author. Thanks again!

**Pull request closed without merging**
